### ISSUE TITLE
Can you add PVE related data?

### ISSUE THREAD

**Issue by otae-1204** [the-hideout/tarkov-api#302]
Hope to add PVE related data, such as fleamarket prices for items, etc

**Comment by Razzmatazzz** [comment]
This is planned, but all of the accounts we use for scanning prices are standard edition and therefore do not have access to PVE. The only current option would be to buy an unheard edition account for $250 (plus taxes and fees) to use for scanning. Because donations to the project aren't even covering current monthly costs, it would be irresponsible to spend that kind of money. Therefore, we're waiting until BSG adds the ability to upgrade any account to have PVE access. Then we can purchase the upgrade for one of the scanner accounts, level it up, and start scanning PVE prices.

**Comment by Shebuka** [comment]
This is now implemented
