### ISSUE TITLE
Inconsistency in price of unavailable items

### ISSUE THREAD

**Issue by Shebuka** [the-hideout/tarkov-api#80]
Currently, for "9x18mm PM RG028 gzh ammo pack (16 pcs)" (as an example), I see this returned:
```
        "changeLast48h": 0,
        "changeLast48hPercent": 0,
        "lastLowPrice": null,
        "low24hPrice": null,
        "avg24hPrice": 0,
        "high24hPrice": null,
```
I expect them to be either all `0` or all `null`, not a mix 😅 Is there any reason for this that I'm missing?

**Comment by Razzmatazzz** [comment]
I agree it should probably be consistent. But there's a case to be made that the `changeLast48h` attributes are correct to be zero instead of null. If there were no prices in the last 48 hours, then the change is zero. But avg24hPrice should probably be null if no prices have been observed in the last 24 hours.

**Comment by Shebuka** [comment]
I see your case. Here are my thoughts about this: a 0 means that there was 0$/% change, like between `1000`$ yesterday and `1000`$ today, while here we have a change between a `null`$ and a `null`$ which I think must give `null` too. This gives us additional info, if the `changeLast48h` is `null` it implies that the _price_ is also `null`; but currently if it's `0` you can't tell and must also check what was the actual price.

**Comment by Razzmatazzz** [comment]
I actually changed this behavior without thinking a bit ago, and returning null instead of 0 broke code for multiple people. While I agree that it makes logical sense for the values to be null when there aren't prices, I think we're already committed to the current state of things in the interest of backwards compatibility.

**Comment by GrantBirki** [comment]
Going to close this out as cleanup
